export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const MARK_NOTE_COMPLETE = 'MARK_NOTE_COMPLETE';
export const MARK_NOTE_ARCHIVE = 'MARK_NOTE_ARCHIVE';
export const MARK_NOTE_TRASH = 'MARK_NOTE_TRASH';
export const DELETE_FROM_TRASH = 'DELETE_FROM_TRASH';
